export const GOOGLE_CLIENT_ID= process.env.GOOGLE_CLIENT_ID || '960407959948-ssptqg2g40r8duu48e848bmbsffe5pl8.apps.googleusercontent.com'
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET || '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'
export const SERVER_ROOT_URI = 'http://localhost:4000'
export const UI_ROOT_URI = 'http://localhost:3000'
export const JWT_SECRET = 'sssh'
export const COOKIE_NAME = 'auth_token'
